app_key: "dw98ddnu1epkbyf"
app_secret: <%= ENV["APP_SECRET"] %>
access_token: "l2enur2mjf8c6uf2"
access_token_secret: <%= ENV["APP_TOKEN_SECRET"] %>
user_id: "324032829"
access_type: "app_folder"


#access_token: l2enur2mjf8c6uf2
#access_token_secret: 5jk3kjttvb40ype
#user_id: 324032829